### ISSUE TITLE
[Native] Exception in thread "main" java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ribasco** [ribasco/ucgdisplay#4]
Error running from Raspberry Pi: 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libucgdisp7530612871061594713.so: /tmp/libucgdisp7530612871061594713.so: undefined symbol: _Z21cb_byte_8bit_6800modeP11u8g2_info_tP11u8x8_structhhPv
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:126)
	at com.ibasco.ucgdisplay.core.utils.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:53)
	at com.ibasco.ucgdisplay.core.u8g2.U8g2Graphics.<clinit>(U8g2Graphics.java:160)
	at com.ibasco.ucgdisplay.drivers.glcd.GlcdBaseDriver.initialize(GlcdBaseDriver.java:132)
	at com.ibasco.ucgdisplay.drivers.glcd.GlcdDriver.<init>(GlcdDriver.java:58)
	at com.ibasco.ucgdisplay.drivers.glcd.GlcdDriver.<init>(GlcdDriver.java:49)
	at com.ibasco.ucgdisplay.drivers.glcd.GlcdDriver.<init>(GlcdDriver.java:41)
	at com.ibasco.ucgdemo.Demo.main(Demo.java:22)
```

**Comment by ribasco** [comment]
Fixed in 9b0a023b8e8c3e8d484de63f832b2e4d84e02c55
